# This is a basic workflow to help you get started with Actions

name: Android Build

# Controls when the workflow will run
on:
 
  # Allows you to run this workflow when called other actions
  workflow_call:
    inputs:
      java_ver:
        type: string
        default: 11
      keystore_path:
        type: string
        required: true
        default: './app/signing'
      keystore_name:
        type: string
        required: true
        default: 'keystore.jks'
      keystore_prop_path:
        type: string
        required: true
        default: './app/signing'
      keystore_prop_name:
        type: string
        required: true
        default: 'keystore.properties'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: set up JDK ${{ inputs.java_ver }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_ver }}
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate Keystore file from GitHub Secrets
      run: |
        mkdir -p ${{ inputs.keystore_path }}
        mkdir -p ${{ inputs.keystore_prop_path }}
        echo '${{ secrets.KEYSTORE_BASE64 }}' | base64 -d > ${{ inputs.keystore_path }}/${{ inputs.keystore_name }}
        echo '${{ secrets.KEYSTORE_PROPERTIES }}' > ${{ inputs.keystore_path }}/${{ inputs.keystore_prop_name }}

    # Notify MS Teams channel
    - uses: toko-bifrost/ms-teams-deploy-card@master
      if: always()
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        card-layout-exit: cozy
        timezone: Asia/Seoul
    
    - name: Build with Gradle
      run: ./gradlew app:assemble

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-artifact
        path: app/build/outputs/apk
        retention-days: 14
