name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_setup:
    name: Build Setup
    # Build setting
    uses: ./.github/workflows/build_setup.yml
    with:
      java_ver: '17'
      keystore_path: './app/signing'
      keystore_name: 'keystore.jks'
      keystore_prop_path: './app/signing'
      keystore_prop_name: 'keystore.properties'
      
  # App test
  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: build_setup

    steps:
    # Test with Gradle
    - name: Test with Gradle
      run: ./gradlew :app:testDebug
      
    # Test Report Upload
    - name: Upload Test
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: app/build/reports/tests/testDebugUnitTest/index.html
        retention-days: 14

  # App build
  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test

    steps:
    # Notify MS Teams channel
    - uses: toko-bifrost/ms-teams-deploy-card@master
      if: always()
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        card-layout-exit: cozy
        timezone: Asia/Seoul
    
    - name: Build with Gradle
      run: ./gradlew build

  # Upload APK
  upload:
    runs-on: ubuntu-latest
    name: Upload APK
    needs: build

    steps:
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-artifact
          path: app/build/outputs/apk
          retention-days: 14
