# This is a basic workflow to help you get started with Actions

name: Android Test

# Controls when the workflow will run
on:
 
  # Allows you to run this workflow when called other actions
  workflow_call:
    inputs:
      java_ver:
        type: string
        default: 11
      keystore_path:
        type: string
        required: true
        default: './app/signing'
      keystore_name:
        type: string
        required: true
        default: 'keystore.jks'
      keystore_prop_path:
        type: string
        required: true
        default: './app/signing'
      keystore_prop_name:
        type: string
        required: true
        default: 'keystore.properties'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_setting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: set up JDK ${{ inputs.java_ver }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_ver }}
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate Keystore file from GitHub Secrets
      run: |
        mkdir -p ${{ inputs.keystore_path }}
        mkdir -p ${{ inputs.keystore_prop_path }}
        echo '${{ secrets.KEYSTORE_BASE64 }}' | base64 -d > ${{ inputs.keystore_path }}/${{ inputs.keystore_name }}
        echo '${{ secrets.KEYSTORE_PROPERTIES }}' > ${{ inputs.keystore_prop_path }}/${{ inputs.keystore_prop_name }}

    # Test with Gradle
    - name: Test with Gradle
      run: ./gradlew :app:testDebug
      
    # Test Report Upload
    - name: Upload Test
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: app/build/reports/tests/testDebugUnitTest/index.html
        retention-days: 14
